//
// Created by Haoyu Gu on 2016-10-06.
//

#ifndef BANK_CONSTANTS_H
#define BANK_CONSTANTS_H

#define MIN_USER_ID_LENGTH 5
#define MIN_USER_PWD_LENGTH 5
#define MAX_USER_ID_LENGTH 1000
#define MAX_USER_PWD_LENGTH 1000

#define MAX_LOGIN_PASSWORD_RETRY 5

#endif //BANK_CONSTANTS_H
